class Symbol
  SYMBOLS = {
      #:PROGRAM => 0,
      #:STMTS => 1,
      #:STMT => 2,
      :SEMI_COL => /;/,
      :PLUS => /\+/,
      :TIMES => /\*/,
      :MINUS => /-/,
      :DIV => /\//,
      #:FACTOR => 5,
      :OPEN_PAREN => /\(/,
      :CLOSE_PAREN => /\)/,
      :LANG_IF => /if/,
      :LANG_THEN => /then/,
      :LANG_END => /end/,
      :LANG_FOR => /for/,
      :LANG_TO => /to/,
      :LANG_FROM => /from/,
      :LANG_ELSE => /else/,
      :LANG_DO => /do/,
      :LANG_BY => /by/,
      #:LOG_EXP => 19,
      #:LOG_TERM => 20,
      :LANG_TRUE => /true/,
      :LANG_FALSE => /false/,
      :LANG_NOT => /not/,
      :LANG_AND => /and/,
      #:LOG_FACTOR => 24,
      :LTE => /<=/,
      :LT => /</,
      :ASSIGN_OP => /:=/,
      :EQ => /=/,
      #:EOF => -1,
      :COMMENT => /(\/\/)(.| )*/,
      :IDENTIFIER => /^[a-zA-Z][a-zA-Z0-9_]*$/,
      :INTEGER => /[0-9]+/,

  }
end